[package]
name = "rt_tunex"
version = "0.5.0"
edition = "2021"
authors = ["Marc Fischer <marcfir@proton.me>"]
license = "MIT OR Apache-2.0"
description = "Systems crate for tuning low-latency and real-time applications in Rust"
keywords = ["low-latency", "linux", "rt", "real-time"]
categories = ["os"]
repository = "https://github.com/marcfir/rt_tunex"

[dependencies]
bitflags = "2.11"


[target.'cfg(target_family = "unix")'.dependencies]
libc = { version = "0.2" }

[target.'cfg(target_os = "macos")'.dependencies]
mach2 = { version = "0.6" }

[target.'cfg(target_os = "linux")'.dependencies]
syscalls = { version = "=0.8.1", features = [
    "x86",
    "x86_64",
    "aarch64",
    "riscv64",
] }

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.62", features = [
    "Win32",
    "Win32_System_Performance",
    "Win32_System_SystemInformation",
    "Win32_System_Memory",
    "Win32_System_Threading",
    "Win32_System_WindowsProgramming",
] }


[dev-dependencies]
nix = { version = "0.31", features = ["process", "sched", "mman"] }
serde_repr = ">=0.1.5"                                              # Unused but forced for -Z minimal-versions
